export enum GroupBuy {
  ORIGNAL_PRICE = "ORIGNAL_PRICE",
  DISCOUNT_TYPE = "DISCOUNT_TYPE",
  DISCOUNT_AMOUNT = "DISCOUNT_AMOUNT",
  DISCOUNT_PERCENTAGE = "DISCOUNT_PERCENTAGE",
  DISCOUNTED_PRICE = "DISCOUNTED_PRICE",
}
