# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54db54a4fb27f00f321bdb1d68ad1a80"
name = "the-splash-app"
handle = "the-splash-app"
application_url = "https://revisions-mining-warning-heath.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robust-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://revisions-mining-warning-heath.trycloudflare.com/auth/callback",
  "https://revisions-mining-warning-heath.trycloudflare.com/auth/shopify/callback",
  "https://revisions-mining-warning-heath.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
