# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16da59d2292fdad94f4c2eaa69577365"
name = "splash-robust-dev"
handle = "splash-robust-dev"
application_url = "https://kind-confused-accent-tan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robust-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_draft_orders,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://kind-confused-accent-tan.trycloudflare.com/auth/callback",
  "https://kind-confused-accent-tan.trycloudflare.com/auth/shopify/callback",
  "https://kind-confused-accent-tan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
