# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9be088b4fe7ae5c62e227fd401c9bef1"
name = "splash-express-app"
handle = "splash-express-app"
application_url = "https://strap-preferences-reservation-salvador.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robust-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://strap-preferences-reservation-salvador.trycloudflare.com/auth/callback",
  "https://strap-preferences-reservation-salvador.trycloudflare.com/auth/shopify/callback",
  "https://strap-preferences-reservation-salvador.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
